"""Answer keys for the synthetic assessments (generated by tools/generate.py)."""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

KEYS_DIR = Path(__file__).resolve().parent / "keys"
_SAFE_ID = re.compile(r"^[A-Za-z0-9_-]{1,64}$")


@lru_cache
def load_key(test_id: str) -> dict[str, str] | None:
    """question_id -> correct letter, or None if no key exists for this test."""
    if not _SAFE_ID.match(test_id or ""):
        return None
    path = KEYS_DIR / f"{test_id}.json"
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))["answers"]
